version: 2
updates:

  # Maintain dependencies for GitHub Actions (main)
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"

  # Maintain dependencies for pip (main)
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
