id: asdf://asdf-format.org/table/manifests/table-1.0.0
extension_uri: asdf://asdf-format.org/table/extensions/table-1.0.0
title: Table extension 1.0.0
description: Tags for ASDF table objects.
asdf_standard_requirement:
  gte: 1.6.0
tags:
- tag_uri: tag:stsci.edu:asdf/table/column-1.1.0
  schema_uri: http://stsci.edu/schemas/asdf/table/column-1.1.0
  title: A column in a table.
  description: |-
    Each column contains a name and an array of data, and an optional description
    and unit.
- tag_uri: tag:stsci.edu:asdf/table/table-1.1.0
  schema_uri: http://stsci.edu/schemas/asdf/table/table-1.1.0
  title: A table.
  description: |-
    A table is represented as a list of columns, where each entry is a
    [column](ref:table/column-1.1.0)
    object, containing the data and some additional information.

    The data itself may be stored inline as text, or in binary in either
    row- or column-major order by use of the `strides` property on the
    individual column arrays.

    Each column in the table must have the same first (slowest moving)
    dimension.
