id: asdf://asdf-format.org/time/manifests/time-1.0.0
extension_uri: asdf://asdf-format.org/time/extensions/time-1.0.0
title: Time extension 1.0.0
description: Tags for ASDF time objects.
asdf_standard_requirement:
  gte: 1.6.0
tags:
- tag_uri: tag:stsci.edu:asdf/time/time-1.2.0
  schema_uri: http://stsci.edu/schemas/asdf/time/time-1.2.0
  title: Represents an instance in time.
  description: |-
    A "time" is a single instant in time.  It may explicitly specify the
    way time is represented (the "format") and the "scale" which
    specifies the offset and scaling relation of the unit of time.

    Specific emphasis is placed on supporting time scales (e.g. UTC,
    TAI, UT1, TDB) and time representations (e.g. JD, MJD, ISO 8601)
    that are used in astronomy and required to calculate, e.g., sidereal
    times and barycentric corrections.

    Times may be represented as one of the following:

    - an object, with explicit `value`, and optional `format`, `scale`
      and `location`.

    - a string, in which case the format is guessed from across
      the unambiguous options (`iso`, `byear`, `jyear`, `yday`), and the
      scale is hardcoded to `UTC`.

    In either case, a single time tag may be used to represent an
    n-dimensional array of times, using either an `ndarray` tag or
    inline as (possibly nested) YAML lists.  If YAML lists, the same
    format must be used for all time values.

    The precision of the numeric formats should only be assumed to be as
    good as an IEEE-754 double precision (float64) value.  If
    higher-precision is required, the `iso` or `yday` format should be
    used.
