id: asdf://asdf-format.org/fits/manifests/fits-1.0.0
extension_uri: asdf://asdf-format.org/fits/extensions/fits-1.1.0
title: Fits extension 1.0.0
description: Tags FITS objects.
asdf_standard_requirement:
  gte: 1.6.0
tags:
- tag_uri: tag:stsci.edu:asdf/fits/fits-1.1.0
  schema_uri: http://stsci.edu/schemas/asdf/fits/fits-1.1.0
  title: A FITS file inside of an ASDF file.
  description: |-
    This schema is useful for distributing ASDF files that can
    automatically be converted to FITS files by specifying the exact
    content of the resulting FITS file.

    Not all kinds of data in FITS are directly representable in ASDF.
    For example, applying an offset and scale to the data using the
    `BZERO` and `BSCALE` keywords.  In these cases, it will not be
    possible to store the data in the native format from FITS and also
    be accessible in its proper form in the ASDF file.

    Only image and binary table extensions are supported.
